services:
  app:
    build: .
    container_name: bank-app
    env_file:
      - .env
    ports:
      - "8090:8090"
    depends_on:
     - postgres
    networks:
      bank-net:
  postgres:
    image: postgres
    container_name: bank-pg
    restart: always
    env_file:
      - .env
    networks:
      bank-net:
    ports:
      - "5431:5432"
    volumes:
      - bank_data:/var/lib/postgresql/data
  pgadmin:
    container_name: bank_pgadmin
    image: dpage/pgadmin4
    ports:
      - "7001:80"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - bank_pgadmin_data:/var/lib/pgadmin
    networks:
      bank-net:

networks:
  bank-net:
    driver: bridge
volumes:
  bank_data:
  bank_pgadmin_data:


